CREATE TABLE HOSPITAL_TBL(
    PATIENT_ID VARCHAR2(12) PRIMARY KEY,
    PATIENT_PWD VARCHAR2(15) NOT NULL,
    PATIENT_NAME VARCHAR2(20)NOT NULL,
    PATIENT_NO NUMBER NOT NULL,
    MEDICAL_COURSE VARCHAR2(30) UNIQUE,
    DOCTOR_NAME VARCHAR2(12)NOT NULL,
    TREATMENT_DIVISION VARCHAR2(6) CHECK(TREATMENT_DIVISION IN('초진','재진')),
    TREATMENT_DATE NUMBER NOT NULL
);

SELECT DOCTOR_NAME, MEDICAL_COURSE
FROM HOSPITAL_TBL JOIN DOCTOR_TBL ON DOCTOR_NAME = DR_NAME;

SELECT * FROM HOSPITAL_TBL;
SELECT * FROM DOCTOR_TBL;

CREATE TABLE DOCTOR_TBL (
    MEDICAL VARCHAR(30) NOT NULL,
    DR_NAME VARCHAR(12) PRIMARY KEY
);
select * from HOSPITAL_TBL;

INSERT INTO DOCTOR_TBL VALUES ('내과','김선민');
INSERT INTO DOCTOR_TBL VALUES ('내과','남재현');
INSERT INTO DOCTOR_TBL VALUES ('내과','김연선');
INSERT INTO DOCTOR_TBL VALUES ('정형외과','이승복');
INSERT INTO DOCTOR_TBL VALUES ('정형외과','양유찬');
INSERT INTO DOCTOR_TBL VALUES ('정형외과','안홍준');
INSERT INTO DOCTOR_TBL VALUES ('방사선과','신석호');
INSERT INTO DOCTOR_TBL VALUES ('방사선과','박중현');
INSERT INTO DOCTOR_TBL VALUES ('방사선과','문태준');
INSERT INTO DOCTOR_TBL VALUES ('정신건강의학과','오은영');
INSERT INTO DOCTOR_TBL VALUES ('정신건강의학과','민병석');
INSERT INTO DOCTOR_TBL VALUES ('정신건강의학과','김익동');
INSERT INTO DOCTOR_TBL VALUES ('산부인과','김소형');
INSERT INTO DOCTOR_TBL VALUES ('산부인과','문정림');
INSERT INTO DOCTOR_TBL VALUES ('산부인과','백광훈');

SELECT * FROM HOSPITAL_TBL;